### ISSUE TITLE
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

### ISSUE THREAD

**Issue by Villelmo** [mariosky/databook#13]
Actually, i try the exercise: 01.ejercicio_python.md. 

When i execute the following command: 

`x = iris[:50,1]`

The result expected is wrong.

**Comment by mariosky** [comment]
Thanks for reporting this error. I need to update the example code, all was written a few years back and
I was using python 2.7.  You must be using python 3.x and they are not compatible. 

Do you speak Spanish?

**Comment by Villelmo** [comment]
Yes, i can speak spanish.

**Comment by Villelmo** [comment]
Yes, i can speak spanish
